export const STORAGE_KEYS = {
  operations: "moneyflow-operations-v1",
  categories: "moneyflow-categories-v1",
  syncSettings: "moneyflow-sync-settings-v1",
  amountsHidden: "moneyflow-amounts-hidden-v1",
  pendingCloudChanges: "moneyflow-pending-cloud-changes-v1",
  cloudPassphrase: "moneyflow-cloud-passphrase-v1",
  cloudEncryptionKey: "moneyflow-cloud-encryption-key-v1",
  cloudEncryptionSalt: "moneyflow-cloud-encryption-salt-v1",
};

export const DEFAULT_CATEGORIES = [];
export const CATEGORY_COLORS = [
  "#EF4444",
  "#F97316",
  "#EAB308",
  "#84CC16",
  "#22C55E",
  "#14B8A6",
  "#06B6D4",
  "#0EA5E9",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#EC4899",
];
export const CURRENT_YEAR_LOOKBACK = 5;

export function createInitialState() {
  return {
    operations: [],
    categories: [...DEFAULT_CATEGORIES],
    syncSettings: {
      googleClientId: "",
      googleFileId: "",
      accessMode: "writer",
      googleAccountEmail: "",
      lastSuccessfulSyncAt: "",
    },
    amountsHidden: false,
    cloudPassphrase: "",
    cloudEncryptionKey: "",
    cloudEncryptionSalt: "",
    hasPendingCloudChanges: false,
    pendingUploadOperationIds: new Set(),
    searchText: "",
    activeTypeFilter: "all",
    activeYearFilter: new Set(),
    activeMonthFilter: new Set(),
    activeDayFilter: new Set(),
    dateFrom: "",
    dateTo: "",
    activeCategoryFilter: new Set(),
    operationType: "income",
    currentPage: 1,
    pageSize: 20,
    categorySearchText: "",
    categoryCurrentPage: 1,
    categorySearchEditing: false,
    quickAddMode: "add",
    quickAddSourceOperationId: "",
    readerPermissions: [],
    sharedReceiptDrafts: [],
  };
}

export function createElements(doc = document) {
  const byId = (id) => doc.getElementById(id);
  return {
    form: byId("operation-form"),
    typeInput: byId("operation-type"),
    typeToggle: byId("operation-type-toggle"),
    categorySelect: byId("operation-category"),
    categoryPicker: byId("category-picker"),
    categoryPickerInput: byId("operation-category-input"),
    categoryPickerToggle: byId("category-picker-toggle"),
    categoryPickerPopover: byId("category-picker-popover"),
    categoryPickerList: byId("category-picker-list"),
    categoryCreateToggleButton: byId("category-create-toggle"),
    categoryCreateNameInput: byId("category-create-name"),
    categoryCreateSaveButton: byId("category-create-save"),
    categoryCreateCancelButton: byId("category-create-cancel"),
    categoryCreateForm: byId("category-create-form"),
    amountInput: byId("operation-amount"),
    amountDisplay: byId("operation-amount-display"),
    amountKeypad: byId("amount-keypad"),
    popularCategories: byId("popular-categories"),
    descriptionInput: byId("operation-description"),
    operationDateInput: byId("operation-date"),
    operationDateDisplay: byId("operation-date-display"),
    operationDatePickerInput: byId("operation-date-picker"),
    operationDatePickerButton: byId("operation-date-picker-button"),
    balanceCurrent: byId("balance-current"),
    lastSuccessfulSync: byId("last-successful-sync"),
    chartsToggleButton: byId("charts-toggle"),
    categoryCharts: byId("category-charts"),
    incomeCategoryChart: byId("income-category-chart"),
    expenseCategoryChart: byId("expense-category-chart"),
    searchSection: byId("search-section"),
    searchToggleButton: byId("search-toggle"),
    searchField: byId("search-field"),
    searchFilters: byId("search-filters"),
    searchInput: byId("search-input"),
    operationsList: byId("operations-list"),
    typeFilterContainer: byId("type-filters"),
    balanceTitle: byId("balance-title"),
    operationsLoadSentinel: byId("operations-load-sentinel"),
    yearFilterContainer: byId("year-filters"),
    monthFilterContainer: byId("month-filters"),
    dayFilterContainer: byId("day-filters"),
    dateFromInput: byId("date-from"),
    dateToInput: byId("date-to"),
    dateFromDisplay: byId("date-from-display"),
    dateToDisplay: byId("date-to-display"),
    dateFromPickerInput: byId("date-from-picker"),
    dateToPickerInput: byId("date-to-picker"),
    categoryFilterContainer: byId("category-filters"),
    syncToggleButton: byId("sync-settings-toggle"),
    syncSettingsCard: byId("sync-settings-section"),
    syncSettingsCloseButton: byId("sync-settings-close"),
    syncGoogleClientIdField: byId("google-client-id-field"),
    instructionsToggleButton: byId("instructions-toggle"),
    instructionsCard: byId("instructions-section"),
    instructionsCloseButton: byId("instructions-close"),
    amountsVisibilityToggleButton: byId("amounts-visibility-toggle"),
    cloudPassphraseInput: byId("cloud-encryption-passphrase"),
    syncGoogleClientIdInput: byId("google-client-id"),
    syncGoogleFileIdInput: byId("google-file-id"),
    syncTabs: byId("sync-tabs"),
    syncEditorTabButton: byId("sync-tab-editor"),
    syncReaderTabButton: byId("sync-tab-reader"),
    syncEditorPanel: byId("sync-editor-panel"),
    syncReaderPanel: byId("sync-reader-panel"),
    readerLinkConnect: byId("reader-link-connect"),
    readerLinkInput: byId("reader-link-input"),
    readerLinkApplyButton: byId("reader-link-apply"),
    syncSaveButton: byId("cloud-save"),
    cloudUploadTopButton: byId("cloud-upload-top"),
    cloudDownloadTopButton: byId("cloud-download-top"),
    cloudUploadButton: byId("cloud-upload"),
    cloudDownloadButton: byId("cloud-download"),
    readerCloudDownloadButton: byId("reader-cloud-download"),
    readerInvite: byId("reader-invite"),
    readerEmailInput: byId("reader-email"),
    readerInviteButton: byId("reader-invite-button"),
    readerInviteStatus: byId("reader-invite-status"),
    readerConnection: byId("reader-connection"),
    readerConnectionLink: byId("reader-connection-link"),
    readerConnectionRefreshButton: byId("reader-connection-refresh"),
    readerConnectionShareButton: byId("reader-connection-share"),
    readerConnectionStatus: byId("reader-connection-status"),
    readerAccessManagement: byId("reader-access-management"),
    readerAccessRefreshButton: byId("reader-access-refresh"),
    readerAccessList: byId("reader-access-list"),
    readerAccessStatus: byId("reader-access-status"),
    syncStatus: byId("cloud-status"),
    appNotice: byId("app-notice"),
    fileExportButton: byId("file-export"),
    fileImportButton: byId("file-import"),
    fileImportInput: byId("file-import-input"),
    clearDataButton: byId("cloud-clear-data"),
    quickAddToggleButton: byId("quick-add-toggle"),
    quickAddCard: byId("quick-add-card"),
    quickAddTitle: byId("quick-add-title"),
    operationSubmitButton: byId("operation-submit"),
    quickAddDismissButton: byId("quick-add-dismiss"),
    sharedReceiptsCard: byId("shared-receipts-card"),
    sharedReceiptsCount: byId("shared-receipts-count"),
    sharedReceiptsList: byId("shared-receipts-list"),
    receiptProcessingOverlay: byId("receipt-processing-overlay"),
    receiptProcessingStatus: byId("receipt-processing-status"),
    receiptScanToggleButton: byId("receipt-scan-toggle"),
    receiptScannerCard: byId("receipt-scanner-card"),
    receiptScannerVideo: byId("receipt-scanner-video"),
    receiptScannerCloseButton: byId("receipt-scanner-close"),
    receiptScannerStatus: byId("receipt-scanner-status"),
  };
}
